vagabonder_web_homepage:
    pattern: /
    defaults: { _controller: VagabonderWebBundle:Default:index }

vagabonder_web_profile:
    path: /my-profile
    defaults: { _controller: VagabonderWebBundle:Default:myProfile }

vagabonder_web_trip_new:
    pattern: /trip/new
    defaults: { _controller: VagabonderWebBundle:Trip:new }

vagabonder_web_trip_new_confirmation:
    pattern: /trip/new/confirmation
    defaults: { _controller: VagabonderWebBundle:Trip:confirmation }