parameters:
#    vagabonder_web.example.class: Vagabonder\WebBundle\Example

services:
#    vagabonder_web.example:
#        class: %vagabonder_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
